server:
  port: 8888

info:
  component: Config Server
spring:
  application:
    name: configserver
  profiles:
    active: developement
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kalasZs/SpringCloud.git
          searchPaths: cloud-config-repo